// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from 'next'
import { prisma } from '../../prisma/client'

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  const {
    positionDesired,
    date,
    fullname,
    gender,
    cityAddress,
    provincialAddress,
    telephone,
    cellphone,
    email,
    dateOfBirth,
    birthOfPlace,
    civilStatus,
    citizenship,
    height,
    weight,
    religion,
    spouse,
    spouseOccupation,
    nameOfChildren1,
    nameOfChildren2,
    nameOfChildren3,
    childBirthDate1,
    childBirthDate2,
    childBirthDate3,
    fatherName,
    fatherOccupation,
    motherName,
    motherOccupation,
    language,
    emergencyContact,
    emergencyAddress,
    elementary,
    elementaryGraduate,
    highschool,
    highschoolGraduate,
    college,
    collegeGraduate,
    degree,
    specialSkills,
    companyName1,
    empPosition1,
    positionFrom1,
    positionTo1,
    companyName2,
    empPosition2,
    positionFrom2,
    positionTo2
  } = req.body

  try {
    await prisma.biodata.create({
      data: {
        positionDesired,
        date,
        fullname,
        gender,
        cityAddress,
        provincialAddress,
        telephone,
        cellphone,
        email,
        dateOfBirth,
        birthOfPlace,
        civilStatus,
        citizenship,
        height,
        weight,
        religion,
        spouse,
        spouseOccupation,
        nameOfChildren1,
        nameOfChildren2,
        nameOfChildren3,
        childBirthDate1,
        childBirthDate2,
        childBirthDate3,
        fatherName,
        fatherOccupation,
        motherName,
        motherOccupation,
        language,
        emergencyContact,
        emergencyAddress,
        elementary,
        elementaryGraduate,
        highschool,
        highschoolGraduate,
        college,
        collegeGraduate,
        degree,
        specialSkills,
        companyName1,
        empPosition1,
        positionFrom1,
        positionTo1,
        companyName2,
        empPosition2,
        positionFrom2,
        positionTo2
      }
    })
    res.status(200).json({ message: 'Data has been added successfully' })
  } catch (error) {
    console.log('Failed')
  }
}
