import './globals.css'

export const metadata = {
  title: 'BIO-DATA',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='bg-gradient-to-r from-rose-100 to-teal-100'>{children}</body>
    </html>
  )
}
